- maven-release-manager/src/test/java/org/apache/maven/shared/release/transform/jdom/JDomPropertiesTest.java
- pom.xml
- clean up ambigous reference in JUnit test
- upgrade Surefire to 2.22.0 to avoid a NullPointerException under Java 10 when executing "mvn package"
> Fixes for MRELEASE-1009:

- maven-release-manager/src/main/java/org/apache/maven/shared/release/DefaultReleaseManager.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/CheckDependencySnapshotsPhase.java
- maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/CheckDependencySnapshotsPhaseTest.java
- maven-release-manager/src/test/resources/projects/check-dependencies/internal-snapshot-dependencies-no-reactor/pom.xml
- Copy properties to the correct release descriptor in DefaultReleaseManager.
- Do not fail the build if the property is resolved from the comand-line (in CheckDependencySnapshotsPhase).
See https://issues.apache.org/jira/browse/MRELEASE-985
> MRELEASE-985 Override snapshot dependencies from command line

- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/RemoveScmTagPhase.java
- maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/RemoveScmTagPhaseTest.java
Hervé, hope this is useful and you pull it in before cutting the release.
> [MRELEASE-1034] changed error to warn if tag is not present at rollback; fixed typos

- maven-release-api/src/main/java/org/apache/maven/shared/release/config/ReleaseDescriptor.java
- maven-release-api/src/main/java/org/apache/maven/shared/release/policy/naming/NamingPolicy.java
- maven-release-api/src/main/java/org/apache/maven/shared/release/policy/version/VersionPolicy.java
- maven-release-api/src/main/java/org/apache/maven/shared/release/strategy/Strategy.java
- maven-release-api/src/main/java/org/apache/maven/shared/release/versions/Version.java
- maven-release-manager/pom.xml
- maven-release-manager/src/main/java/org/apache/maven/shared/release/ReleaseManager.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/exec/ForkedMavenExecutor.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/CheckDependencySnapshotsPhase.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/MapVersionsPhase.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/scm/ScmTranslator.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/util/PomFinder.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/versions/DefaultVersionInfo.java
- maven-release-plugin/src/main/java/org/apache/maven/plugins/release/PrepareReleaseMojo.java
- maven-release-plugin/src/test/java/org/apache/maven/plugins/release/stubs/FlatMultiModuleMavenProjectStub.java
https://issues.apache.org/jira/browse/MRELEASE-1036
- Fix Javadocs
- To be compatible with the JDK 8 doclint
✅`mvn javadoc:javadoc`
> [MRELEASE-1036] Fix JavaDoc for JDK 8

- maven-release-plugin/src/site/fml/faq.fml
On the documentation website, the "project.scm.id" example in the "How can I hide my username and password?"
section is missing a slash for the closing tag.
This PR adds the slash.
See: https://maven.apache.org/maven-release/maven-release-plugin/faq.html#credentials
> (doc) Fix missing slash for closing tag in FAQs

- maven-release-api/src/main/java/org/apache/maven/shared/release/versions/MavenArtifactVersion.java
Initially I planned to work on suspicious call
https://github.com/apache/maven-release/blob/d91b784796e93171171bbcd27c2dc7c97a186c82/maven-release-api/src/main/java/org/apache/maven/shared/release/versions/MavenArtifactVersion.java#L43
but after closer inspection this happened.
> Change interface implemented by MavenArtifactVersion

- maven-release-manager/src/main/mdo/release-descriptor.mdo
```
$ wget https://codehaus-plexus.github.io/modello/xsd/modello-1.4.0.xsd
$ 
$ git checkout 48094bdb
$ xmlstarlet val -s modello-1.4.0.xsd -e maven-release-manager/src/main/mdo/release-descriptor.mdo
maven-release-manager/src/main/mdo/release-descriptor.mdo:22.140: Element '{https://codehaus-plexus.github.io/MODELLO/1.4.0}model': No matching global declaration available for the validation root.
maven-release-manager/src/main/mdo/release-descriptor.mdo - invalid
$ 
$ git checkout 0f4a5a8c
$ xmlstarlet val -s modello-1.4.0.xsd -e maven-release-manager/src/main/mdo/release-descriptor.mdo
maven-release-manager/src/main/mdo/release-descriptor.mdo - valid
```
> Fix xsd NS

- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/MapVersionsPhase.java
- maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/MapVersionsPhaseTest.java
this also works with version passed as arguments on the command line.
I was facing https://issues.apache.org/jira/browse/MRELEASE-1022, as trying to follow the documentation https://maven.apache.org/maven-release/maven-release-plugin/examples/non-interactive-release.html would not work (the multi-module & using properties file in particular)
I went and looked at the code, added test that would reproduce, and fixed them. 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
Please let me know if you'd rather I file a contributor license.
> [MRELEASE-1022] Use versions defined in `release.properties` when doing `release:prepare`

- maven-release-manager/pom.xml
- maven-release-manager/src/main/java/org/apache/maven/shared/release/exec/InvokerMavenExecutor.java
- maven-release-manager/src/test/java/org/apache/maven/shared/release/exec/InvokerMavenExecutorTest.java
> [MRELEASE-1085] Upgrade Maven Invoker to 3.2.0

- maven-release-manager/pom.xml
- maven-release-manager/src/main/java/org/apache/maven/shared/release/config/ReleaseDescriptorBuilder.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/exec/InvokerMavenExecutor.java
- maven-release-manager/src/test/java/org/apache/maven/shared/release/config/ReleaseDescriptorBuilderTest.java
- maven-release-manager/src/test/java/org/apache/maven/shared/release/exec/InvokerMavenExecutorTest.java
- maven-release-plugin/src/it/projects/prepare/MRELEASE-667/verify.groovy
> [MRELEASE-1088] Remove parsing of CLI arguments

- maven-release-manager/src/main/java/org/apache/maven/shared/release/exec/InvokerMavenExecutor.java
> [MRELEASE-1091] Use non-interactive mode for forked Maven process

- maven-release-api/pom.xml
- maven-release-manager/pom.xml
- maven-release-plugin/pom.xml
- maven-release-policies/maven-release-oddeven-policy/pom.xml
- pom.xml
> [MRELEASE-1094] Clean up dependencies

- maven-release-manager/src/main/java/org/apache/maven/shared/release/DefaultReleaseManager.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/exec/ForkedMavenExecutor.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/exec/InvokerMavenExecutor.java
- maven-release-plugin/pom.xml
- maven-release-plugin/src/it/projects/stage/MRELEASE-1104-both-parameters/invoker.properties
- maven-release-plugin/src/it/projects/stage/MRELEASE-1104-both-parameters/pom.xml
- maven-release-plugin/src/it/projects/stage/MRELEASE-1104-both-parameters/verify.groovy
- maven-release-plugin/src/it/projects/stage/MRELEASE-1104-stage-repo-only/invoker.properties
- maven-release-plugin/src/it/projects/stage/MRELEASE-1104-stage-repo-only/pom.xml
- maven-release-plugin/src/it/projects/stage/MRELEASE-1104-stage-repo-only/verify.groovy
- maven-release-plugin/src/test/java/org/apache/maven/plugins/release/StageReleaseMojoTest.java
Signed-off-by: Olivier Lamy <olamy@apache.org>
To make clear that …
> [MRELEASE-1104] fix stage goal when having both arguments and stagingRepository

- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/RewritePomsForDevelopmentPhase.java
- maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/RewritePomsForDevelopmentPhaseTest.java
- maven-release-manager/src/test/resources/projects/rewrite-for-development/basic-pom-with-svn-from-tag/expected-pom.xml
- maven-release-manager/src/test/resources/projects/rewrite-for-development/basic-pom-with-svn-from-tag/pom.xml
- pom.xml
https://issues.apache.org/jira/browse/MRELEASE-1072
translator does not support resolving
please ask …
> MRELEASE-1072 reuse original tag for next development version in case

- maven-release-manager/src/main/java/org/apache/maven/shared/release/exec/ForkedMavenExecutor.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/exec/InvokerMavenExecutor.java
- maven-release-plugin/src/main/java/org/apache/maven/plugins/release/AbstractReleaseMojo.java
I don't know why this bug does not get fixed. The documentation clearly says that you can use the argument `-DjavaHome=` to set the path to your jdk, but this parameter is not used anywhere in the code, thereby completely ignored. This is a huge pain for people who are using CI/CD servers (for example jenkins) with multiple jdks installed. In that case the release plugin is not usable.
So I adjusted the InvokerMavenExecutor so that it honors the `javaHome` argument.
> [MRELEASE-851]: javaHome argument is now honored in InvokerMavenExecutor

- maven-release-api/src/main/java/org/apache/maven/shared/release/config/ReleaseDescriptor.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/GenerateReleasePomsPhase.java
- maven-release-plugin/pom.xml
- maven-release-plugin/src/it/projects/branch/MRELEASE-458/pom.xml
- maven-release-plugin/src/it/projects/branch/MRELEASE-694/verify.groovy
- maven-release-plugin/src/it/projects/branch/MRELEASE-745/pom.xml
- maven-release-plugin/src/it/projects/branch/MRELEASE-976/verify.groovy
- maven-release-plugin/src/it/projects/perform/MRELEASE-592/pom.xml
- maven-release-plugin/src/it/projects/prepare/MRELEASE-1053/verify.groovy
- maven-release-plugin/src/it/projects/prepare/MRELEASE-1077/pom.xml
- maven-release-plugin/src/it/projects/prepare/MRELEASE-1077/verify.groovy
- maven-release-plugin/src/it/projects/prepare/MRELEASE-161-dependencyManagement/verify.groovy
- maven-release-plugin/src/it/projects/prepare/MRELEASE-161/verify.groovy
- maven-release-plugin/src/it/projects/prepare/MRELEASE-571_M3/module1/pom.xml
- maven-release-plugin/src/it/projects/prepare/MRELEASE-667/pom.xml
- maven-release-plugin/src/it/projects/prepare/MRELEASE-667/verify.groovy
- maven-release-plugin/src/it/projects/prepare/MRELEASE-976/verify.groovy
- maven-release-plugin/src/it/projects/prepare/MRELEASE-985/verify.groovy
- maven-release-plugin/src/it/projects/prepare/namespace/verify.groovy
- maven-release-plugin/src/it/projects/prepare/version-policy/verify.groovy
- maven-release-plugin/src/it/projects/update-versions/MRELEASE-555/verify.groovy
- maven-release-plugin/src/it/projects/update-versions/MRELEASE-611/verify.groovy
- maven-release-plugin/src/it/projects/update-versions/MRELEASE-976/verify.groovy
- maven-release-plugin/src/main/java/org/apache/maven/plugins/release/BranchReleaseMojo.java
- maven-release-plugin/src/main/java/org/apache/maven/plugins/release/PrepareReleaseMojo.java
- maven-release-plugin/src/main/java/org/apache/maven/plugins/release/UpdateVersionsMojo.java
- pom.xml
> [MRELEASE-1123] Fix for Maven 4 compatibility

- maven-release-plugin/src/main/java/org/apache/maven/plugins/release/StageReleaseMojo.java
> prefer JDK String replace methods to Plexus ones

- maven-release-manager/pom.xml
- maven-release-plugin/pom.xml
- pom.xml
Cures dependency warnings but still selects the right version of hamcrest-core in transitive dependencies. See https://hamcrest.org/JavaHamcrest/distributables
> fixup hamcrest dependencies

- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/AbstractRewritePomsPhase.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/transform/jdom2/JDomModel.java
- maven-release-manager/src/test/resources/projects/rewrite-for-release/pom-with-parent-and-cifriendly-expressions/expected-pom.xml
> [MRELEASE-1109] patch JDomModel

- maven-release-api/src/main/java/org/apache/maven/shared/release/config/ReleaseDescriptor.java
- maven-release-manager/src/main/java/org/apache/maven/shared/release/scm/DefaultScmRepositoryConfigurator.java
Clarify precedence of credentials resolved via settings and those explicitly given.
please ask on the …
> [MRELEASE-1139] Improve logging of sources for used credentials

- pom.xml
This closes #216
To make clear that you license your contribution …
> [MRELEASE-1144] Upgrade to Parent 42

- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/GenerateReleasePomsPhase.java
- maven-release-manager/src/test/resources/projects/generate-release-poms/internal-snapshot-dependencies/subproject4/expected-release-pom.xml
- maven-release-manager/src/test/resources/projects/generate-release-poms/internal-snapshot-dependencies/subproject4/subsubproject/expected-release-pom.xml
This closes #219
To make clear that you license your contribution …
> [MRELEASE-1148] Release Manage pulls in transitive dependencies

- maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/AbstractRewritePomsPhase.java
- maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/AbstractRewritePomsPhaseTest.java
expressions
To make clear that you license your contribution under …
> [MRELEASE-1154] Never fail for unresolvable version expressions
